# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Loom version (shared across all MC versions)
loom_version=1.9-SNAPSHOT

# Mod Properties (shared across all MC versions)
mod_version=0.7.2
maven_group=com.wickedsik
archives_base_name=pocketislands
