modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/WickedCoding/mc-pocket-islands/issues"

[[mods]]
modId = "personalworlds"
version = "${version}"
displayName = "Pocket Islands"
displayURL = "https://modrinth.com/mod/pocket-islands"
logoFile = "assets/personalworlds/icon.png"
authors = "Jurriën"
description = '''Give each player their own pocket dimension island that survives world resets'''

[[mixins]]
config = "pocketislands.mixins.json"

[[dependencies.personalworlds]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.personalworlds]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
