# Minecraft 1.21.11 NeoForge specific properties
# Check https://projects.neoforged.net/neoforged/neoforge for updates

minecraft_version=1.21.11
parchment_version=2025.12.20
neoforge_version=21.11.45

# Dependencies for 1.21.11 NeoForge
infiniverse_version=21.11.1

# Java toolchain for compiling and running 1.21.11
java_version=21
