# Minecraft 1.20.1 Forge specific properties
# Check https://files.minecraftforge.net for updates

minecraft_version=1.20.1
parchment_version=2023.09.03
forge_version=47.4.10

# Dependencies for 1.20.1 Forge
infiniverse_version=1.0.0.5

# Java toolchain for compiling and running 1.20.1
java_version=17
